select
    CDR_DT_DIM_ID,
	OU_DIM_ID,
	AC_EXPN,
	ACG_DT,
	TXN_TP,
	CARD_EXPN_AMT_FCY,
	ACG_ENTR,
	REMARK_1,
	REMARK_2,
	CARD_TP,
	GRP_FEE_ID,
	FEE_TP_ID,
	AC_CR   
FROM (	
select 	
	CDR_DT_DIM.CDR_DT_DIM_ID CDR_DT_DIM_ID,
	OU_DIM.OU_DIM_ID OU_DIM_ID,
	CCARD_EXPN_ANL_FCT.AC_EXPN AC_EXPN,
	CCARD_EXPN_ANL_FCT.ACG_DT ACG_DT,
	CCARD_EXPN_ANL_FCT.TXN_TP TXN_TP,
	CCARD_EXPN_ANL_FCT.CARD_EXPN_AMT_FCY CARD_EXPN_AMT_FCY,
	CCARD_EXPN_ANL_FCT.ACG_ENTR ACG_ENTR,
	CCARD_EXPN_ANL_FCT.REMARK_1 REMARK_1,
	CCARD_EXPN_ANL_FCT.REMARK_2 REMARK_2,
	CCARD_EXPN_ANL_FCT.CARD_TP CARD_TP,
	FEE_TP_DIM.FEE_TP_DIM_ID GRP_FEE_ID,
	FEE_TP_DIM1.FEE_TP_DIM_ID FEE_TP_ID,
	CCARD_EXPN_ANL_FCT.AC_CR AC_CR 
from	(((DMT.TWT_CARD_EXPN_ANL_FCT CCARD_EXPN_ANL_FCT  INNER JOIN  DMT.CDR_DT_DIM CDR_DT_DIM  
    ON  1=1 AND  CDR_DT_DIM.CDR_DT_DIM_ID =  #EIB_DWH.v_prj_pcs_date_yyyymmdd
     )  LEFT OUTER JOIN  DMT.OU_DIM OU_DIM  
    ON  OU_DIM.ANCHOR_ID =  CCARD_EXPN_ANL_FCT.OU_ID
AND  OU_DIM.EFF_FM_DT <= TO_DATE( #EIB_DWH.v_prj_pcs_date_yyyymmdd, 'YYYYMMDD')
AND OU_DIM.EFF_TO_DT > TO_DATE( #EIB_DWH.v_prj_pcs_date_yyyymmdd, 'YYYYMMDD')
     )  LEFT OUTER JOIN  DMT.FEE_TP_DIM FEE_TP_DIM  
    ON  CCARD_EXPN_ANL_FCT.GRP_FEE_CODE = FEE_TP_DIM.FEE_CODE
     )  LEFT OUTER JOIN  DMT.FEE_TP_DIM FEE_TP_DIM1  
    ON  CCARD_EXPN_ANL_FCT.FEE_TP_CODE =  FEE_TP_DIM1.FEE_CODE
where		(1=1)	
)  ODI_GET_FROM