--testg
--test new branch
select
    OU_ID,
	AC_EXPN,
	ACG_DT,
	TXN_TP,
	CARD_EXPN_AMT_FCY,
	ACG_ENTR,
	REMARK_1,
	REMARK_2,
	CARD_TP,
	GRP_FEE_CODE,
	FEE_TP_CODE,
	AC_CR   
FROM (	
select 	
	TWT_PST_ENTR_FEE.OU_ID OU_ID,
	TWT_PST_ENTR_FEE.AR_NBR AC_EXPN,
	TWT_PST_ENTR_FEE.PST_DT ACG_DT,
	TWT_PST_ENTR_FEE.ACG_EFF_TP_ID TXN_TP,
	TWT_PST_ENTR_FEE.PST_ENTR_AMT_FCY CARD_EXPN_AMT_FCY,
	REGEXP_SUBSTR(TWT_PST_ENTR_FEE.UNQ_ID_IN_SRC_STM,'([^.]+)',1,2) ACG_ENTR,
	TWT_PST_ENTR_FEE.DSC||TWT_PST_ENTR_FEE.DSC2 REMARK_1,
	TWT_PST_ENTR_FEE.ADT_DLT_INFO REMARK_2,
	TWT_EXPN_TP.PRD_TP CARD_TP,
	TWT_EXPN_TP.FEE_GRP_CODE GRP_FEE_CODE,
	TWT_EXPN_TP.FEE_TP_CODE FEE_TP_CODE,
	NVL( OUTPUTSIGNATURE_0302300101_R.AR_NBR ,OUTPUTSIGNATURE_0302300101_R_1.AR_NBR) AC_CR 
from	((AWM.TWT_PST_ENTR_FEE TWT_PST_ENTR_FEE  LEFT OUTER JOIN  AWM.TWT_EXPN_TP TWT_EXPN_TP  
    ON  TWT_EXPN_TP.PST_ENTR_ID =  TWT_PST_ENTR_FEE.PST_ENTR_ID
     )  LEFT OUTER JOIN  (SELECT * FROM (SELECT 
             ABC.TRAN_ID,
             ABC.AR_NBR,
	ABC.ACG_EFF_TP_ID,
             ROW_NUMBER () OVER(PARTITION BY ABC.TRAN_ID ORDER BY ABC.AR_NBR ASC) RNK1
  FROM 
     (SELECT * FROM (SELECT 
       REGEXP_SUBSTR(A.UNQ_ID_IN_SRC_STM,'([^.]+)',1,2) TRAN_ID,
        AR.AR_NBR AR_NBR,
        A.PST_ENTR_AMT_FCY PST_ENTR_AMT_FCY,
        A.ACG_EFF_TP_ID ACG_EFF_TP_ID,
        RANK() OVER(PARTITION BY REGEXP_SUBSTR(A.UNQ_ID_IN_SRC_STM,'([^.]+)',1,2) ORDER BY A.PST_ENTR_AMT_FCY DESC) RNK
         FROM AWM.TWT_PST_ENTR_CARD_EXPN A
         JOIN AWM.AR ON AR.AR_ID = A.AC_AR_ID
         JOIN AWM.CCY ON CCY.CCY_ID = A.CCY_ID
      JOIN AWM.TWT_PST_ENTR_FEE N ON REGEXP_SUBSTR(A.UNQ_ID_IN_SRC_STM,'([^.]+)',1,2) =    REGEXP_SUBSTR(N.UNQ_ID_IN_SRC_STM,'([^.]+)',1,2)  
         AND N.ACG_EFF_TP_ID <> A.ACG_EFF_TP_ID
         WHERE CCY.CCY_CODE = 'VND'  ) 
         WHERE RNK = 1) ABC
   )WHERE RNK1 = 1) OUTPUTSIGNATURE_0302300101_R_1  
    ON  REGEXP_SUBSTR(TWT_PST_ENTR_FEE.UNQ_ID_IN_SRC_STM,'([^.]+)',1,2) =  OUTPUTSIGNATURE_0302300101_R_1.TRAN_ID
AND  OUTPUTSIGNATURE_0302300101_R_1.ACG_EFF_TP_ID <> TWT_PST_ENTR_FEE.ACG_EFF_TP_ID
     )  LEFT OUTER JOIN  (SELECT * FROM (SELECT 
             ABC.TRAN_ID,
             ABC.AR_NBR,
	ABC.ACG_EFF_TP_ID,
             ROW_NUMBER () OVER(PARTITION BY ABC.TRAN_ID ORDER BY ABC.AR_NBR DESC) RNK1
  FROM 
     (SELECT * FROM (SELECT 
       REGEXP_SUBSTR(A.UNQ_ID_IN_SRC_STM,'([^.]+)',1,2) TRAN_ID,
        AR.AR_NBR AR_NBR,
        A.PST_ENTR_AMT_FCY PST_ENTR_AMT_FCY,
        A.ACG_EFF_TP_ID ACG_EFF_TP_ID,
        RANK() OVER(PARTITION BY REGEXP_SUBSTR(A.UNQ_ID_IN_SRC_STM,'([^.]+)',1,2) ORDER BY A.PST_ENTR_AMT_FCY DESC) RNK
         FROM AWM.TWT_PST_ENTR_CARD_EXPN A
         JOIN AWM.AR ON AR.AR_ID = A.AC_AR_ID
         JOIN AWM.CCY ON CCY.CCY_ID = A.CCY_ID
         WHERE CCY.CCY_CODE <> 'VND'  ) 
         WHERE RNK = 1) ABC
   )WHERE RNK1 = 1) OUTPUTSIGNATURE_0302300101_R  
    ON  REGEXP_SUBSTR(TWT_PST_ENTR_FEE.UNQ_ID_IN_SRC_STM,'([^.]+)',1,2) = OUTPUTSIGNATURE_0302300101_R.TRAN_ID  
AND  OUTPUTSIGNATURE_0302300101_R.ACG_EFF_TP_ID <> TWT_PST_ENTR_FEE.ACG_EFF_TP_ID
where		(1=1)	
) 