select
    AR_NBR,
	PST_ENTR_ID,
	OU_ID,
	ACG_STC_ITM_ID,
	PST_DT,
	ACG_EFF_TP_ID,
	PST_ENTR_AMT_FCY,
	UNQ_ID_IN_SRC_STM,
	DSC,
	DSC2,
	ADT_DLT_INFO   
FROM (	
select 	
	AR.AR_NBR AR_NBR,
	PST_ENTR.PST_ENTR_ID PST_ENTR_ID,
	PST_ENTR.OU_ID OU_ID,
	PST_ENTR.ACG_STC_ITM_ID ACG_STC_ITM_ID,
	PST_ENTR.PST_DT PST_DT,
	PST_ENTR.ACG_EFF_TP_ID ACG_EFF_TP_ID,
	PST_ENTR.PST_ENTR_AMT_FCY PST_ENTR_AMT_FCY,
	PST_ENTR.UNQ_ID_IN_SRC_STM UNQ_ID_IN_SRC_STM,
	PST_ENTR.DSC DSC,
	PST_ENTR.DSC2 DSC2,
	PST_ENTR.ADT_DLT_INFO ADT_DLT_INFO 
from	AWM.AR AR  INNER JOIN  AWM.PST_ENTR PST_ENTR  
    ON  PST_ENTR.AC_AR_ID = AR.AR_ID
where		(1=1)	
 and (SUBSTR(AR.AR_NBR, 5, 10) IN(
  '0081103000', '0081103001', '0081103002', 
  '0081103003', '0081103004', '0081103005', 
  '0081103006', '0081103007', '0080901006')) and (TO_CHAR(PST_ENTR.PST_DT, 'YYYYMMDD') = #EIB_DWH.v_prj_pcs_date_yyyymmdd
AND DECODE(PST_ENTR.ITT_EMPE_ID, 'EOD1', PST_ENTR.ITT_EMPE_ID, 
'EOD2', PST_ENTR.ITT_EMPE_ID, PST_ENTR.VFD_USER_CODE) IS NOT NULL)
) 